[[redirects]]
  from = "/settings"
  to = "/"
  status = 200
[[redirects]]
  from = "/messenger"
  to = "/"
  status = 200
[[redirects]]
  from = "/sign-up"
  to = "/"
  status = 200
[[redirects]]
  from = "/404/"
  to = "/"
  status = 200
[[redirects]]
  from = "/500/"
  to = "/"
  status = 200
<<<<<<< HEAD
[[redirects]]
  from = "/static/form.css"
  to = "../static/form.css"
  status = 200
  [[redirects]]
  from = "/static/color.css"
  to = "../static/color.css"
  status = 200
=======
>>>>>>> main
