[[redirects]]
  from = "/settings/"
  to = "/"
  status = 200
  force = false
  query = {path = ":path"}
  conditions = {Language = ["ru"], Country = ["RU"], Role = ["guest"]}

[[redirects]]
  from = "/login/"
  to = "/"
  status = 200
[[redirects]]
  from = "/reg/"
  to = "/"
  status = 200
[[redirects]]
  from = "/404/"
  to = "/"
  status = 200
[[redirects]]
  from = "/500/"
  to = "/"
  status = 200
