export { LoginPage } from './form_auth'
export { RegistrationPage } from './form_registration'
export { default as ChatsPage } from './index/index'
export { ErrorPage404 } from './404'
export { ErrorPage500 } from './500'
export { SettingsPage } from './settings'
